name: WeChat New Year Countdown

on:
  schedule:
    # 每天北京时间早上8点运行
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  send_countdown:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run countdown script
      env:
        WECHAT_APPID: ${{ secrets.WECHAT_APPID }}
        WECHAT_APPSECRET: ${{ secrets.WECHAT_APPSECRET }}
        WECHAT_TEMPLATE_ID: ${{ secrets.WECHAT_TEMPLATE_ID }}
        WECHAT_TOUSER: ${{ secrets.WECHAT_TOUSER }}
      run: |
        python wechat_countdown.py
